### ISSUE TITLE
Fingerprint Screen Unlock Delay

### ISSUE THREAD

**Issue by ToucH9000** [chiteroman/android_kernel_xiaomi_sm8150#1]
I am using LineageOS 19.1 ... To reproduce, you just need to leave the phone for two to three minutes in locked state and then try to put your thumb on sensor, after putting your thumb on the sensor it's suppose to unlock the screen but for me it's not unlocking until i lift my thumb from the sensor. I had no issues on previous LineageOS kernel named as perf.

Edit : Before flashing this new kernel, i repacked zip file with dtb and dtbo file from previous lineage kernel who's ksu was 11510

**Comment by chiteroman** [comment]
Uhhh, weird. Can you test this?
[AnyKernel3.zip](https://github.com/chiteroman/android_kernel_xiaomi_sm8150/files/14348803/AnyKernel3.zip)

Don't modify dtb and dtbo.

**Comment by ToucH9000** [comment]
> Don't modify dtb and dtbo.

Still same issue, i haven't modified anything.

**Comment by chiteroman** [comment]
I'm compiling Lineage kernel, maybe it's more stable 🤔
https://github.com/chiteroman/android_kernel_xiaomi_vayu

**Comment by chiteroman** [comment]
[lineage_no_ksu.zip](https://github.com/chiteroman/android_kernel_xiaomi_sm8150/files/14352013/lineage_no_ksu.zip)

@ToucH9000 Try this, it doesn't have KernelSU.

**Comment by ToucH9000** [comment]
> [lineage_no_ksu.zip](https://github.com/chiteroman/android_kernel_xiaomi_sm8150/files/14352013/lineage_no_ksu.zip)
> 
> @ToucH9000 Try this, it doesn't have KernelSU.

It's working without any issue.

**Comment by ToucH9000** [comment]
Issue is completely fixed [HERE](https://github.com/chiteroman/android_kernel_xiaomi_vayu/releases/tag/latest). UwU

**Comment by chiteroman** [comment]
Can you try latest update ? https://github.com/chiteroman/android_kernel_xiaomi_sm8150/releases/tag/latest

**Comment by ToucH9000** [comment]
> Can you try latest update ? https://github.com/chiteroman/android_kernel_xiaomi_sm8150/releases/tag/latest

Having unlock delay issue. :C

**Comment by chiteroman** [comment]
I think this is a problem of rom, in MIUI I don't have any delay with that kernel :/

Just use lineage kernel ^^
